#!/usr/bin/env node
'use strict';

// What the Android app takes from the desktop app, so the two cannot drift apart:
//
//   desktop/shell/icons.js     -> res/drawable/ic_<id>.xml   the marks on the rail (and the launcher icon)
//   desktop/src/services.js    -> assets/services.json       which services, where, what each may do
//   desktop/src/extractors.js  -> assets/extractors.js       what "Capture page" runs inside the page
//   desktop/shell/shell.css    -> res/values/hole_colors.xml the palette
//
// Run `node android/tools/sync.js` after changing any of those. desktop/test/android-sync.test.js
// fails when the generated files are out of date.

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..', '..');
const MAIN = path.join(__dirname, '..', 'app', 'src', 'main');

const { ICONS } = require(path.join(ROOT, 'desktop', 'shell', 'icons.js'));
const { BUILTIN } = require(path.join(ROOT, 'desktop', 'src', 'services.js'));
const extractors = require(path.join(ROOT, 'desktop', 'src', 'extractors.js'));

// The dark ink on an orange tile is written out in shell.css (.active, button.primary), not named.
const INK = '#1a0e07';
const NOTE = 'Generated by android/tools/sync.js. Do not edit; change the desktop file it reads and run the script again.';

// ---------------------------------------------------------------- paths

const ARITY = { M: 2, L: 2, H: 1, V: 1, C: 6, S: 4, Q: 4, T: 2, A: 7, Z: 0 };
const NUMBER = /^[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?/;
const FLAG = /^[01]/;

// SVG lets a path run its numbers together ("a1 1 0 011 1": two flags, then 1 1) and repeat a
// command by leaving its letter out. Android's parser is stricter about both, so write every
// segment out in full: one letter, then its numbers separated by spaces.
function normalisePath(d) {
  const out = [];
  let i = 0;
  const skip = () => {
    while (i < d.length && /[\s,]/.test(d[i])) i += 1;
  };
  for (;;) {
    skip();
    if (i >= d.length) break;
    const letter = d[i];
    if (!/[MmLlHhVvCcSsQqTtAaZz]/.test(letter)) throw new Error(`path: unexpected "${letter}" at ${i}`);
    i += 1;
    const kind = letter.toUpperCase();
    if (!ARITY[kind]) {
      out.push(letter);
      continue;
    }
    for (let group = 0; ; group += 1) {
      skip();
      if (i >= d.length || !/[-+.\d]/.test(d[i])) {
        if (group === 0) throw new Error(`path: "${letter}" has no numbers at ${i}`);
        break;
      }
      const numbers = [];
      for (let k = 0; k < ARITY[kind]; k += 1) {
        skip();
        const match = (kind === 'A' && (k === 3 || k === 4) ? FLAG : NUMBER).exec(d.slice(i));
        if (!match) throw new Error(`path: expected a number at ${i}, found "${d.slice(i, i + 10)}"`);
        numbers.push(match[0]);
        i += match[0].length;
      }
      // A moveto followed by more pairs means linetos.
      const used = group === 0 || kind !== 'M' ? letter : letter === 'M' ? 'L' : 'l';
      out.push(used + numbers.join(' '));
    }
  }
  return out.join('');
}

// ---------------------------------------------------------------- files

const vector = (d, { size = 24, fill = '#FFFFFFFF', group = null } = {}) => {
  const path = `<path
        android:fillColor="${fill}"
        android:pathData="${normalisePath(d)}" />`;
  const body = group
    ? `<group
        android:scaleX="${group.scale}"
        android:scaleY="${group.scale}"
        android:translateX="${group.x}"
        android:translateY="${group.y}">
        ${path}
    </group>`
    : path;
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${NOTE} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${size}dp"
    android:height="${size}dp"
    android:viewportWidth="${size}"
    android:viewportHeight="${size}">
    ${body}
</vector>
`;
};

// The launcher draws the ring in a 108 dp square of which only the middle 66 dp is sure to be
// seen, so it is scaled to the same share of the tile as in desktop/assets/icon.png (outer radius
// .27 of the side) and centred.
function launcherForeground() {
  const scale = Math.round((0.27 * 108 / 9) * 1000) / 1000;
  const shift = Math.round((54 - 12 * scale) * 1000) / 1000;
  return vector(ICONS.hole, { size: 108, fill: `#FF${INK.slice(1).toUpperCase()}`, group: { scale, x: shift, y: shift } });
}

function colours() {
  const css = fs.readFileSync(path.join(ROOT, 'desktop', 'shell', 'shell.css'), 'utf8');
  const root = /:root\s*\{([^}]*)\}/.exec(css);
  if (!root) throw new Error('shell.css has no :root block');
  const vars = {};
  for (const [, name, value] of root[1].matchAll(/--([a-z-]+):\s*(#[0-9a-fA-F]{6})\s*;/g)) vars[name] = value.toUpperCase();
  for (const need of ['bg', 'panel', 'line', 'text', 'muted', 'accent', 'bad', 'good']) {
    if (!vars[need]) throw new Error(`shell.css :root has no --${need}`);
  }
  if (!css.toLowerCase().includes(INK)) throw new Error(`shell.css no longer uses ${INK} for text on the accent`);
  const rows = [...Object.entries(vars), ['ink', INK.toUpperCase()]]
    .map(([name, value]) => `    <color name="hole_${name.replace(/-/g, '_')}">${value}</color>`)
    .join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${NOTE} -->
<resources>
${rows}
</resources>
`;
}

function servicesJson() {
  const rows = BUILTIN.map(({ id, name, glyph, url, level, extractors: names }) => ({ id, name, glyph, url, level, extractors: names }));
  return `${JSON.stringify(rows, null, 2)}\n`;
}

// The extractors are plain functions with no closures (the desktop app serialises each into the page),
// so their source can be carried over as it is. holeExtract is the same merge-then-fall-back-to-the-page
// as extract() in extractors.js, minus the driver.
function extractorsJs() {
  const { EXTRACTORS, dedupe } = extractors;
  const names = Object.keys(EXTRACTORS);
  return `// ${NOTE}
${names.map((name) => EXTRACTORS[name].toString()).join('\n\n')}

const EXTRACTORS = { ${names.join(', ')} };

${dedupe.toString()}

function holeExtract(names) {
  const found = [];
  for (const name of names) {
    if (EXTRACTORS[name]) found.push(...EXTRACTORS[name]());
  }
  const items = dedupe(found);
  return items.length ? items : page();
}
`;
}

// Everything this script writes, as { path relative to app/src/main: contents }.
function generate() {
  const files = {
    'assets/services.json': servicesJson(),
    'assets/extractors.js': extractorsJs(),
    'res/values/hole_colors.xml': colours(),
    'res/drawable/ic_launcher_foreground.xml': launcherForeground(),
  };
  for (const [id, d] of Object.entries(ICONS)) files[`res/drawable/ic_${id}.xml`] = vector(d);
  // A Windows checkout can hold the desktop sources with CRLF line ends, and function source
  // carries them through; what is committed should not depend on whose machine wrote it.
  for (const file of Object.keys(files)) files[file] = files[file].replace(/\r\n/g, '\n');
  return files;
}

if (require.main === module) {
  for (const [file, content] of Object.entries(generate())) {
    const target = path.join(MAIN, file);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content);
    console.log('wrote', path.relative(ROOT, target));
  }
}

module.exports = { generate, normalisePath, MAIN };
